# web 访问端口
server:
  port: 8090
  servlet:
    context-path: /api
    session:
      timeout: PT60M # session 过期时间 60M一个小时

spring:
  application:
    name: easypan
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/first_db?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.ppcola.easypan.entity # 别名扫描包
  global-config:
    db-config:
      id-type: auto
